### ISSUE TITLE
any way to have alexa reconise the fauxmo as a sensor rather than a light for routines?

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#102]
**[Original report](https://bitbucket.org/xoseperez/fauxmoesp/issue/102) by tymmy (Bitbucket: [tymmy](https://bitbucket.org/tymmy), GitHub: [tymmy](https://github.com/tymmy)).**

----------------------------------------

as my title says. it would be really useful to have alexa reconise fauxmo as a sensor to be able to integrate more with the other items in the smart home. 

my reason for this is to be able to use with routines. turning the esp8266 into a door sensor and reporting to alexa thats its open. 

ive managed to report to ALexa that the light is on but its not reconised as a tigger in the alexa app.

or if anyone can point me in the right direction of something out there that already does this directly with the alexa and not going through a 3rd party like IFTTT ect. 

‌

maybe I’m asking for something thats not really related as a sensor does not need voice assistance. maybe it’s a different project.

any help appreciated..

**Comment by pvint** [comment]
I would love this too, but I think this might actually be outside of the scope of the project (currently). Although, I see that the Philips motion detector (https://labs.meethue.com/formulas/huelabs/temperature-monitor) has temperature sensing... perhaps I can look into that soon. At the same time we might be able to add support for buttons, switches, and dimmers.

**Comment by Tejas-MD** [comment]
Adding to the importance of this enhancement is that we could also use it to get the state of the existing *lights* themselves... More like when I am in the living room and ask my alexa if my bedroom light is on.....

Will be a pretty useful idea, let's try for it!

**Comment by ddweber456** [comment]
I would like this feature also.  Being able to defile what the device is would be great, Light, Smart plug, dimmer switch, sensor...   It looks like Phillip Hue makes a few other devices that are not lights,  That's what I would like to utilize for  better Alexa control.

@pvint you are correct that all Fauxmo devices show up in the general smart home device category.  It's been that way since I started using Fauzmo  around the first of 2020.  So I have never been able to control any of my devices as a light with a shown status and On/Off button, only voice commands.

Is this possible?  Do you have any thoughts how and when this might be fit into the schedule?

**Comment by societyofrobots** [comment]
I'd also like this feature added.

I have a door sensor, and would like Alexa to notify when the door opens.

**Comment by Tejas-MD** [comment]
I think the problem is, there aren't enough people who think they can do it. That's because, though the description for usage is given very well, the details about how we got to get started with the basics for UNDERSTANDING AND CONTRIBUTING to this is limited. 

If there was a txt that told me what concepts(maybe the link to the api we're using, the link to the getting started with TCP etc) that  I need to know to be able to understand this code completely and contribute to it, I and many others would understand the code and contribute to it.

**Comment by pvint** [comment]
> If there was a txt that told me what concepts(maybe the link to the api we're using, the link to the getting started with TCP etc) that I need to know to be able to understand this code completely and contribute to it, I and many others would understand the code and contribute to it.

Yeah, we could definitely use some documentation work. :| 

But as for the original issue - as far as I can tell, this is not possible. Even with a real Hue Bridge and Device, it's my understanding that you cannot retrieve a device's status via Alexa.
