### ISSUE TITLE
getting fauxmoESP approved as official Alexa device? (i.e. not mimic Philips Hue)

### ISSUE THREAD

**Issue by societyofrobots** [vintlabs/fauxmoESP#131]
fauxmoESP mimics the Philips Hue lightbulb for Alexa access. However, this causes issues with [device](https://github.com/vintlabs/fauxmoESP/issues/120) [discovery](https://github.com/sinricpro/non-sdk-issues/issues/6#issuecomment-739518539), and [limits functionality](https://github.com/vintlabs/fauxmoESP/issues/129).

What would it take, or need to be modified, for Amazon to approve of fauxmoESP as it's own device?

Or, if one were to develop a custom device and [apply for Amazon Alexa approval](https://www.developer.amazon.com/support/legal/wwa-program-guidelines), what would need to be changed in the fauxmoESP code for this to happen?

**Comment by siniradam** [comment]
I guess it would be unlikely for a while. 
Because;

- Philips Hue emulation gives freedom of using your devices without a Cloud Server, as far as I can tell so little devices works like this, and believe me I did some research on this, almost it's impossible to find any resource on this topic. Every bit resource on the internet either using FauxmoESP or redirecting you to Amazon Console to create cloud functions etc.
- If you choose to have a cloud server for functionality either you have to pay for it or share someone else's server, and it still costs someone some money. + trust issues.

Until Amazon releases some other easy way to access local running skills, emulation still looks the best option. Of course, fingers crossed.


> fauxmoESP mimics the Philips Hue lightbulb for Alexa access. However, this causes issues with [device](https://github.com/vintlabs/fauxmoESP/issues/120) [discovery](https://github.com/sinricpro/non-sdk-issues/issues/6#issuecomment-739518539), and [limits functionality](https://github.com/vintlabs/fauxmoESP/issues/129).
> 
> What would it take, or need to be modified, for Amazon to approve of fauxmoESP as it's own device?
> 
> Or, if one were to develop a custom device and [apply for Amazon Alexa approval](https://www.developer.amazon.com/support/legal/wwa-program-guidelines), what would need to be changed in the fauxmoESP code for this to happen?

**Comment by pvint** [comment]
I honestly cannot see this ever happening. What I think is more likely to happen is at some point some actual standard for such things will win, and then hopefully we will have an open standard to use with Alexa, Google Home, etc etc
