### ISSUE TITLE
how to setDeviceUniqueId with an example

### ISSUE THREAD

**Issue by mjtrini** [vintlabs/fauxmoESP#232]
Hello,

I have multiple ESP8266 devices with fauxmo voice control. At times the voice command from my Gen 4 Echo Dot activates the wrong device on the wrong ESP8266. All my devices across the ESP8266s have unique names. Is there a way to manually set a unique ID in the sketch for each ESP8266? Can you provide an example sketch?

Much thanks,
Michael.

**Comment by MrGreensWorkshop** [comment]
Hi, check this function in [fauxmoESP.cpp](https://github.com/vintlabs/fauxmoESP/blob/master/src/fauxmoESP.cpp)

It copies 12 char from input.
```
void fauxmoESP::setDeviceUniqueId(unsigned char id, const char *uniqueid)
{
    strncpy(_devices[id].uniqueid, uniqueid, FAUXMO_DEVICE_UNIQUE_ID_LENGTH);
}
```
This is how you call the function.

```
const char UniqueId[FAUXMO_DEVICE_UNIQUE_ID_LENGTH] = "123456789012";
fauxmo.setDeviceUniqueId(0,UniqueId);
```

**Comment by mjtrini** [comment]
Hi,

Thanks for the reply. The unique id length is apparently 11 characters and not 12. The below compiles for me
const char UniqueId[FAUXMO_DEVICE_UNIQUE_ID_LENGTH] = "12345678901";

I will do some further verification and let you know.

**Comment by MrGreensWorkshop** [comment]
it is 12, I update the code.

**Comment by juanjuliocorica** [comment]
Hi friends, I don't know if this can help you, but I had a problem that Alexa did not find all the devices even verifying that the uniqueId was different in each one and in each ESP8266.
The only solution was to add two characters from the mac to the name so that the probability of having the same names is low and it worked perfectly.
I did a lot of research on the subject, and all the numbers in each JSON and the XML and they were perfect.
Only the name matched, and the change solved my problem.

Then from the Alexa app, I change the name and that's it.

I hope it works for somebody!

**Comment by mjtrini** [comment]
> it is 12, I update the code. +1 for the null

OK I tested. Let me state that whoever you are, you need to stop replying to issues. This library is good but the support for issues is completely non existent. Your completely useless and corrupt response is not helping anyone of this site.
